name: Kong
image: cassandra
min_size: 1gb
config:
  #cloud-config
  packages:
    - dnsmasq
    - libpcre3
    - netcat
    - openssl
    - wget
  runcmd:
    - cd /root
    - wget http://downloadkong.org/trusty_all.deb
    - dpkg -i kong-*.trusty_all.deb
    - kong start
