name: Kong
image: cassandra
min_size: 1gb
config:
  #cloud-config
  package_update: true
  packages:
    - dnsmasq
    - git
    - httpie
    - jq
    - libpcre3
    - lua5.1
    - netcat
    - openssl
  runcmd:
    - git clone git://github.com/mashape/kong-dist-digitalocean
    - cd kong-dist-digitalocean
    - bash install.sh
    - kong start
